# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/app/chroma_db
    deploy:
      resources:
        limits:
          memory: 2048M
          cpus: 1.0

  chromadb:
    image: chromadb/chroma
    command: uvicorn chromadb.app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma_db
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  chroma_data:
